#requires -Version 5.1
[CmdletBinding()]
param([switch]$FirstRun)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$configDir = Join-Path $root 'config'
$localConfigPath = Join-Path $configDir 'local.psd1'

function Get-ConfiguredPath {
    if (-not (Test-Path -LiteralPath $localConfigPath)) { return $null }
    try {
        $local = Import-PowerShellDataFile -LiteralPath $localConfigPath
        if (-not $local.LlamaServerPath) { return $null }
        $path = [Environment]::ExpandEnvironmentVariables([string]$local.LlamaServerPath)
        if (Test-Path -LiteralPath $path -PathType Leaf) {
            return (Resolve-Path -LiteralPath $path).Path
        }
    } catch {}
    return $null
}

function Get-Candidates {
    $seen = @{}
    $result = New-Object System.Collections.Generic.List[string]

    function Add-Candidate {
        param([string]$Path)
        if ([string]::IsNullOrWhiteSpace($Path)) { return }
        try {
            $expanded = [Environment]::ExpandEnvironmentVariables($Path)
            if (-not (Test-Path -LiteralPath $expanded -PathType Leaf)) { return }
            $resolved = (Resolve-Path -LiteralPath $expanded).Path
            $key = $resolved.ToLowerInvariant()
            if (-not $seen.ContainsKey($key)) {
                $seen[$key] = $true
                [void]$result.Add($resolved)
            }
        } catch {}
    }

    Add-Candidate (Get-ConfiguredPath)
    Add-Candidate $env:QWEN_LLAMA_SERVER
    Add-Candidate (Join-Path $root 'llama.cpp\llama-server.exe')

    $command = Get-Command 'llama-server.exe' -ErrorAction SilentlyContinue
    if ($command) { Add-Candidate $command.Source }

    $searchRoots = @('C:\AI\llama.cpp')
    if ($env:LOCALAPPDATA) { $searchRoots += (Join-Path $env:LOCALAPPDATA 'llama.cpp') }
    if ($env:USERPROFILE) { $searchRoots += (Join-Path $env:USERPROFILE 'llama.cpp') }

    foreach ($searchRoot in $searchRoots) {
        if (-not (Test-Path -LiteralPath $searchRoot -PathType Container)) { continue }
        Get-ChildItem -LiteralPath $searchRoot -Filter 'llama-server.exe' -File -Recurse -ErrorAction SilentlyContinue |
            ForEach-Object { Add-Candidate $_.FullName }
    }

    return @($result)
}

function Test-Candidate {
    param([Parameter(Mandatory)][string]$Path)

    $backend = 'Unknown'
    if ($Path -match '(?i)vulkan') { $backend = 'Vulkan' }
    elseif ($Path -match '(?i)rocm|hip') { $backend = 'ROCm/HIP' }

    $version = ''
    $devices = ''
    $works = $false
    $gpuReady = $false

    try {
        $version = (& $Path --version 2>&1 | Out-String).Trim()
        $devices = (& $Path --list-devices 2>&1 | Out-String).Trim()
        $works = $true
        if ($devices -match '(?im)^\s+\S*\d+:' -and $devices -notmatch '(?im)^\s*\(none\)\s*$') {
            $gpuReady = $true
        }
    } catch {
        $devices = $_.Exception.Message
    }

    return [pscustomobject]@{
        Path = $Path
        Backend = $backend
        Version = $version
        Devices = $devices
        Works = $works
        GpuReady = $gpuReady
    }
}

function Save-PathConfig {
    param([Parameter(Mandatory)][string]$Path)

    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    $escaped = $Path.Replace("'", "''")
    $content = "@{`r`n    # Generated by Qwen Local Launcher. This file is ignored by Git.`r`n    LlamaServerPath = '$escaped'`r`n}`r`n"
    $encoding = New-Object Text.UTF8Encoding($false)
    [IO.File]::WriteAllText($localConfigPath, $content, $encoding)
}

$existing = Get-ConfiguredPath
if ($FirstRun -and $existing) { exit 0 }

[System.Windows.Forms.Application]::EnableVisualStyles()

$form = New-Object System.Windows.Forms.Form
$form.Text = 'Qwen Local Launcher - llama.cpp setup'
$form.StartPosition = 'CenterScreen'
$form.Size = New-Object System.Drawing.Size(900, 540)
$form.MinimumSize = New-Object System.Drawing.Size(760, 480)
$form.Font = New-Object System.Drawing.Font('Segoe UI', 10)

$title = New-Object System.Windows.Forms.Label
$title.Text = 'Choose llama-server.exe'
$title.Font = New-Object System.Drawing.Font('Segoe UI Semibold', 17)
$title.AutoSize = $true
$title.Location = New-Object System.Drawing.Point(24, 20)
$form.Controls.Add($title)

$subtitle = New-Object System.Windows.Forms.Label
$subtitle.Text = 'Detected builds are tested with --version and --list-devices. Prefer GPU ready.'
$subtitle.AutoSize = $true
$subtitle.Location = New-Object System.Drawing.Point(27, 58)
$form.Controls.Add($subtitle)

$list = New-Object System.Windows.Forms.ListView
$list.Location = New-Object System.Drawing.Point(28, 92)
$list.Size = New-Object System.Drawing.Size(825, 180)
$list.View = [System.Windows.Forms.View]::Details
$list.FullRowSelect = $true
$list.HideSelection = $false
[void]$list.Columns.Add('Status', 110)
[void]$list.Columns.Add('Backend', 105)
[void]$list.Columns.Add('Path', 585)
$form.Controls.Add($list)

$details = New-Object System.Windows.Forms.TextBox
$details.Location = New-Object System.Drawing.Point(28, 288)
$details.Size = New-Object System.Drawing.Size(825, 130)
$details.Multiline = $true
$details.ReadOnly = $true
$details.ScrollBars = 'Vertical'
$form.Controls.Add($details)

$browse = New-Object System.Windows.Forms.Button
$browse.Text = 'Browse...'
$browse.Size = New-Object System.Drawing.Size(110, 34)
$browse.Location = New-Object System.Drawing.Point(28, 438)
$form.Controls.Add($browse)

$cancel = New-Object System.Windows.Forms.Button
$cancel.Text = 'Cancel'
$cancel.Size = New-Object System.Drawing.Size(100, 34)
$cancel.Location = New-Object System.Drawing.Point(642, 438)
$cancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.Controls.Add($cancel)

$save = New-Object System.Windows.Forms.Button
$save.Text = 'Save'
$save.Size = New-Object System.Drawing.Size(100, 34)
$save.Location = New-Object System.Drawing.Point(753, 438)
$save.Enabled = $false
$form.Controls.Add($save)
$form.AcceptButton = $save
$form.CancelButton = $cancel

$infos = New-Object System.Collections.Generic.List[object]

function Add-Info {
    param($Info)
    [void]$infos.Add($Info)
    $status = if ($Info.GpuReady) { 'GPU ready' } elseif ($Info.Works) { 'No GPU' } else { 'Error' }
    $item = New-Object System.Windows.Forms.ListViewItem($status)
    [void]$item.SubItems.Add($Info.Backend)
    [void]$item.SubItems.Add($Info.Path)
    $item.Tag = $infos.Count - 1
    [void]$list.Items.Add($item)
}

foreach ($candidate in (Get-Candidates)) {
    Add-Info (Test-Candidate -Path $candidate)
}

$list.add_SelectedIndexChanged({
    if ($list.SelectedItems.Count -eq 0) {
        $save.Enabled = $false
        $details.Text = ''
        return
    }
    $info = $infos[[int]$list.SelectedItems[0].Tag]
    $save.Enabled = $info.Works
    $details.Text = "Backend: $($info.Backend)`r`nPath: $($info.Path)`r`n`r`n$($info.Version)`r`n`r`n$($info.Devices)"
})

$browse.add_Click({
    $dialog = New-Object System.Windows.Forms.OpenFileDialog
    $dialog.Title = 'Select llama-server.exe'
    $dialog.Filter = 'llama-server.exe|llama-server.exe|Executables (*.exe)|*.exe'
    if ($dialog.ShowDialog($form) -eq [System.Windows.Forms.DialogResult]::OK) {
        $path = $dialog.FileName
        $found = $false
        foreach ($info in $infos) {
            if ($info.Path -ieq $path) { $found = $true; break }
        }
        if (-not $found) { Add-Info (Test-Candidate -Path $path) }
        foreach ($item in $list.Items) {
            if ($item.SubItems[2].Text -ieq $path) {
                $item.Selected = $true
                break
            }
        }
    }
    $dialog.Dispose()
})

$save.add_Click({
    if ($list.SelectedItems.Count -eq 0) { return }
    $info = $infos[[int]$list.SelectedItems[0].Tag]
    if (-not $info.Works) { return }
    Save-PathConfig -Path $info.Path
    $form.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $form.Close()
})

$preferred = $null
foreach ($item in $list.Items) {
    $info = $infos[[int]$item.Tag]
    if ($info.GpuReady) { $preferred = $item; break }
}
if (-not $preferred -and $list.Items.Count -gt 0) { $preferred = $list.Items[0] }
if ($preferred) { $preferred.Selected = $true }

$result = $form.ShowDialog()
$form.Dispose()

if ($result -eq [System.Windows.Forms.DialogResult]::OK) { exit 0 }
exit 2
