#requires -Version 5.1
[CmdletBinding()]
param(
    [switch]$FirstRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$configDir = Join-Path $root 'config'
$localConfigPath = Join-Path $configDir 'local.psd1'

function Get-ExistingConfiguredPath {
    if (-not (Test-Path -LiteralPath $localConfigPath)) { return $null }
    try {
        $local = Import-PowerShellDataFile -LiteralPath $localConfigPath
        if ($local.LlamaServerPath -and (Test-Path -LiteralPath ([Environment]::ExpandEnvironmentVariables([string]$local.LlamaServerPath))) ) {
            return (Resolve-Path -LiteralPath ([Environment]::ExpandEnvironmentVariables([string]$local.LlamaServerPath)).Path
        }
    } catch {}
    return $null
}

function Get-CandidatePaths {
    $seen = @{}
    $result = New-Object System.Collections.Generic.List[string]

    function Add-Candidate([string]$Path) {
        if (-not $Path) { return }
        try {
            $expanded = [Environment]::ExpandEnvironmentVariables($Path)
            if (-not (Test-Path -LiteralPath $expanded -PathType Leaf)) { return }
            $resolved = (Resolve-Path -LiteralPath $expanded).Path
            $key = $resolved.ToLowerInvariant()
            if (-not $seen.ContainsKey($key)) {
                $seen[$key] = $true
                [void]$result.Add($resolved)
            }
        } catch {}
    }

    Add-Candidate (Get-ExistingConfiguredPath)
    Add-Candidate $env:QWEN_LLAMA_SERVER
    Add-Candidate (Join-Path $root 'llama.cpp\llama-server.exe')

    $command = Get-Command 'llama-server.exe' -ErrorAction SilentlyContinue
    if ($command) { Add-Candidate $command.Source }

    $commonRoots = @(
        'C:\AI\llama.cpp',
        (Join-Path $env:LOCALAPPDATA 'llama.cpp'),
        (Join-Path $env:USERPROFILE 'llama.cpp')
    )

    foreach ($searchRoot in $commonRoots) {
        if (-not $searchRoot -or -not (Test-Path -LiteralPath $searchRoot -PathType Container)) { continue }
        Get-ChildItem -LiteralPath $searchRoot -Filter 'llama-server.exe' -File -Recurse -ErrorAction SilentlyContinue |
            ForEach-Object { Add-Candidate $_.FullName }
    }

    return @($result)
}

function Get-LlamaServerInfo {
    param([Parameter(Mandatory)][string]$Path)

    $backend = 'Unknown'
    if ($Path -match '(?i)vulkan') { $backend = 'Vulkan' }
    elseif ($Path -match '(?i)rocm|hip') { $backend = 'ROCm/HIP' }

    $version = ''
    $devices = ''
    $works = $false
    $gpuReady = $false

    try {
        $version = (& $Path --version 2>&1 | Out-String).Trim()
        $devices = (& $Path --list-devices 2>&1 | Out-String).Trim()
        $works = $true
        if ($devices -and $devices -notmatch '(?im)^\s*\(none\)\s*$' -and $devices -match '(?im)^\s+\S+\d*:') {
            $gpuReady = $true
        }
    } catch {
        $devices = $_.Exception.Message
    }

    [pscustomobject]@{
        Path = $Path
        Backend = $backend
        Version = $version
        Devices = $devices
        Works = $works
        GpuReady = $gpuReady
    }
}

function Save-LlamaServerPath {
    param([Parameter(Mandatory)][string]$Path)
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    $escaped = $Path.Replace("'", "''")
    $content = "@{`r`n    # Generated by scripts/configure-llama.ps1. This file is ignored by Git.`r`n    LlamaServerPath = '$escaped'`r`n}`r`n"
    [IO.File]::WriteAllText($localConfigPath, $content, (New-Object Text.UTF8Encoding($false)))
}

$existing = Get-ExistingConfiguredPath
if ($FirstRun -and $existing) { exit 0 }

[System.Windows.Forms.Application]::EnableVisualStyles()
$form = New-Object System.Windows.Forms.Form
$form.Text = 'Qwen Local Launcher - llama.cpp setup'
$form.StartPosition = 'CenterScreen'
$form.Size = New-Object System.Drawing.Size(900, 540)
$form.MinimumSize = New-Object System.Drawing.Size(760, 480)
$form.Font = New-Object System.Drawing.Font('Segoe UI', 10)
$form.BackColor = [System.Drawing.Color]::FromArgb(245, 246, 248)

$title = New-Object System.Windows.Forms.Label
$title.Text = 'Choose llama-server.exe'
$title.Font = New-Object System.Drawing.Font('Segoe UI Semibold', 17)
$title.AutoSize = $true
$title.Location = New-Object System.Drawing.Point(24, 20)
$form.Controls.Add($title)

$subtitle = New-Object System.Windows.Forms.Label
$subtitle.Text = 'Detected builds are tested automatically. Prefer a build marked GPU ready.'
$subtitle.AutoSize = $true
$subtitle.Location = New-Object System.Drawing.Point(27, 58)
$form.Controls.Add($subtitle)

$list = New-Object System.Windows.Forms.ListView
$list.Location = New-Object System.Drawing.Point(28, 92)
$list.Size = New-Object System.Drawing.Size(825, 180)
$list.Anchor = 'Top,Left,Right'
$list.View = [System.Windows.Forms.View]::Details
$list.FullRowSelect = $true
$list.HideSelection = $false
[void]$list.Columns.Add('Status', 110)
[void]$list.Columns.Add('Backend', 105)
[void]$list.Columns.Add('Path', 585)
$form.Controls.Add($list)

$details = New-Object System.Windows.Forms.TextBox
$details.Location = New-Object System.Drawing.Point(28, 288)
$details.Size = New-Object System.Drawing.Size(825, 130)
$details.Anchor = 'Top,Bottom,Left,Right'
$details.Multiline = $true
$details.ReadOnly = $true
$details.ScrollBars = 'Vertical'
$details.BackColor = [System.Drawing.Color]::White
$form.Controls.Add($details)

$browse = New-Object System.Windows.Forms.Button
$browse.Text = 'Browse...'
$browse.Size = New-Object System.Drawing.Size(110, 34)
$browse.Location = New-Object System.Drawing.Point(28, 438)
$browse.Anchor = 'Bottom,Left'
$form.Controls.Add($browse)

$cancel = New-Object System.Windows.Forms.Button
$cancel.Text = 'Cancel'
$cancel.Size = New-Object System.Drawing.Size(100, 34)
$cancel.Location = New-Object System.Drawing.Point(642, 438)
$cancel.Anchor = 'Bottom,Right'
$cancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.Controls.Add($cancel)

$save = New-Object System.Windows.Forms.Button
$save.Text = 'Save'
$save.Size = New-Object System.Drawing.Size(100, 34)
$save.Location = New-Object System.Drawing.Point(753, 438)
$save.Anchor = 'Bottom,Right'
$save.Enabled = $false
$form.Controls.Add($save)
$form.AcceptButton = $save
$form.CancelButton = $cancel

$infos = New-Object System.Collections.Generic.List[object]

function Add-InfoToList($info) {
    [void]$infos.Add($info)
    $status = if ($info.GpuReady) { 'GPU ready' } elseif ($info.Works) { 'No GPU' } else { 'Error' }
    $item = New-Object System.Windows.Forms.ListViewItem($status)
    [void]$item.SubItems.Add($info.Backend)
    [void]$item.SubItems.Add($info.Path)
    $item.Tag = $infos.Count - 1
    [void]$list.Items.Add($item)
}

foreach ($candidate in (Get-CandidatePaths)) {
    Add-InfoToList (Get-LlamaServerInfo -Path $candidate)
}

$list.add_SelectedIndexChanged({
    if ($list.SelectedItems.Count -eq 0) {
        $save.Enabled = $false
        $details.Text = ''
        return
    }
    $index = [int]$list.SelectedItems[0].Tag
    $info = $infos[$index]
    $save.Enabled = $info.Works
    $details.Text = "Backend: $($info.Backend)`r`nPath: $($info.Path)`r`n`r`n$($info.Version)`r`n`r`n$($info.Devices)"
})

$browse.add_Click({
    $dialog = New-Object System.Windows.Forms.OpenFileDialog
    $dialog.Title = 'Select llama-server.exe'
    $dialog.Filter = 'llama-server.exe|llama-server.exe|Executable files (*.exe)|*.exe'
    $dialog.CheckFileExists = $true
    if ($dialog.ShowDialog($form) -eq [System.Windows.Forms.DialogResult]::OK) {
        $path = $dialog.FileName
        $already = $false
        foreach ($info in $infos) { if ($info.Path -ieq $path) { $already = $true; break } }
        if (-not $already) { Add-InfoToList (Get-LlamaServerInfo -Path $path) }
        foreach ($item in $list.Items) {
            if ($item.SubItems[2].Text -ieq $path) { $item.Selected = $true; $item.EnsureVisible(); break }
        }
    }
    $dialog.Dispose()
})

$save.add_Click({
    if ($list.SelectedItems.Count -eq 0) { return }
    $index = [int]$list.SelectedItems[0].Tag
    $info = $infos[$index]
    if (-not $info.Works) { return }
    Save-LlamaServerPath -Path $info.Path
    $form.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $form.Close()
})

$preferred = $null
foreach ($item in $list.Items) {
    $idx = [int]$item.Tag
    if ($infos[$idx].GpuReady) { $preferred = $item; break }
}
if (-not $preferred -and $list.Items.Count -gt 0) { $preferred = $list.Items[0] }
if ($preferred) { $preferred.Selected = $true }

$result = $form.ShowDialog()
$form.Dispose()

if ($result -eq [System.Windows.Forms.DialogResult]::OK) { exit 0 }
exit 2
