#requires -Version 5.1
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Root,
    [string]$HostAddress = '127.0.0.1',
    [int]$Port = 8080,
    [string]$Profile = '',
    [switch]$SelfTest
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$script:LogDir=Join-Path $Root 'logs';$script:PidPath=Join-Path $Root 'runtime\llama-server.pid';$script:ErrorLog=Join-Path $script:LogDir 'runtime-diagnostics-error.log'
function Write-DiagnosticsError{param([object]$ErrorRecord);try{New-Item -ItemType Directory -Force -Path $script:LogDir|Out-Null;Add-Content -LiteralPath $script:ErrorLog -Encoding UTF8 -Value "[$(Get-Date -Format o)] $($ErrorRecord|Out-String)"}catch{}}
function Get-SafeProperty{param([object]$Object,[string]$Name,$Default=$null);if($null -eq $Object){return $Default};$p=$Object.PSObject.Properties[$Name];if($null -eq $p){return $Default};return $p.Value}
function Get-JsonEndpoint{param([string]$Path);try{return Invoke-RestMethod -Uri "http://${HostAddress}:$Port$Path" -TimeoutSec 2}catch{return $null}}
function Get-TextEndpoint{param([string]$Path);try{return [string](Invoke-WebRequest -Uri "http://${HostAddress}:$Port$Path" -UseBasicParsing -TimeoutSec 2).Content}catch{return $null}}
function Get-CommandText{$path=Join-Path $script:LogDir 'last-command.txt';if(Test-Path -LiteralPath $path -PathType Leaf){return(Get-Content -LiteralPath $path -Raw).Trim()};return 'No command recorded yet.'}
function Get-CommandFlagValue{param([string]$Command,[string]$Flag);if([string]::IsNullOrWhiteSpace($Command)){return $null};$pattern='(?:^|\s)'+[regex]::Escape($Flag)+'\s+(?:"(?<q>[^"]+)"|(?<u>\S+))';$m=[regex]::Match($Command,$pattern);if(-not$m.Success){return $null};if($m.Groups['q'].Success){return$m.Groups['q'].Value};return$m.Groups['u'].Value}
function Get-CurrentProcessInfo{if(-not(Test-Path -LiteralPath $script:PidPath -PathType Leaf)){return $null};try{$pidValue=[int](Get-Content -LiteralPath $script:PidPath -Raw).Trim();$p=Get-Process -Id $pidValue -ErrorAction Stop;$ded=$null;$shared=$null;try{[object[]]$rows=@(Get-CimInstance Win32_PerfFormattedData_GPUPerformanceCounters_GPUProcessMemory -ErrorAction Stop|Where-Object{$_.Name -match "pid_${pidValue}_"});if($rows.Length -gt 0){$ded=[math]::Round((($rows|Measure-Object DedicatedUsage -Sum).Sum)/1MB,1);$shared=[math]::Round((($rows|Measure-Object SharedUsage -Sum).Sum)/1MB,1)}}catch{};return[pscustomobject]@{Pid=$p.Id;WorkingSetMB=[math]::Round($p.WorkingSet64/1MB,1);PrivateMB=[math]::Round($p.PrivateMemorySize64/1MB,1);CpuSeconds=[math]::Round($p.CPU,1);Threads=$p.Threads.Count;GpuDedicatedMB=$ded;GpuSharedMB=$shared}}catch{return $null}}
function Get-SystemMemoryInfo{try{$os=Get-CimInstance Win32_OperatingSystem -ErrorAction Stop;$total=[math]::Round([double]$os.TotalVisibleMemorySize/1024,0);$avail=[math]::Round([double]$os.FreePhysicalMemory/1024,0);$commit=$null;$limit=$null;try{$perf=Get-CimInstance Win32_PerfFormattedData_PerfOS_Memory -ErrorAction Stop;$commit=[math]::Round([double]$perf.CommittedBytes/1MB,0);$limit=[math]::Round([double]$perf.CommitLimit/1MB,0)}catch{};return[pscustomobject]@{TotalMB=$total;UsedMB=$total-$avail;AvailableMB=$avail;CommitMB=$commit;CommitLimitMB=$limit}}catch{return $null}}
function Get-LatestStderrLog{return Get-ChildItem -LiteralPath $script:LogDir -Filter '*.stderr.log' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1}
function Format-MiB{param([double]$Value,[bool]$Seen);if(-not$Seen){return 'not captured in current log'};return('{0:N1} MiB'-f$Value)}
function Get-LogAnalysis{
 param([string[]]$Lines,[string]$SourceName='')
 if($null -eq $Lines){$latest=Get-LatestStderrLog;if(-not$latest){return[pscustomobject]@{Summary='No llama.cpp stderr log found yet.';Raw='No llama.cpp stderr log found yet.'}};$SourceName=$latest.Name;[string[]]$Lines=@(Get-Content -LiteralPath $latest.FullName -ErrorAction Stop)}
 $tot=@{GPUModel=0.0;CPUModel=0.0;GPUKV=0.0;CPUKV=0.0;GPUCompute=0.0;CPUCompute=0.0;GPUOutput=0.0;CPUOutput=0.0};$seen=@{GPUModel=$false;CPUModel=$false;GPUKV=$false;CPUKV=$false;GPUCompute=$false;CPUCompute=$false;GPUOutput=$false;CPUOutput=$false};$gpuLayers=$null;$totalLayers=$null;$runtimeContext=$null;$nBatch=$null;$nUbatch=$null;$mmprojPath=$null;$mmprojBackend='unknown';$mtp=$false;$imageWarning=$false;$interesting=New-Object Collections.Generic.List[string]
 foreach($line in $Lines){
  if($line -match '(?i)(offload|buffer size|KV|compute|Vulkan|CUDA|ROCm|HIP|mmproj|mtmd|CLIP|vision|draft|MTP|speculat|n_ctx|n_batch|n_ubatch|image tokens|prompt eval|eval time|tokens per second|flash)'){$interesting.Add($line)}
  if($line -match '(?i)(?<device>[A-Za-z0-9_:\[\].-]+)\s+model buffer size\s*=\s*(?<size>[0-9.]+)\s*MiB'){$where=if($matches.device-match'(?i)CPU|Host'){'CPU'}else{'GPU'};$k="${where}Model";$tot[$k]+=[double]$matches.size;$seen[$k]=$true}
  if($line -match '(?i)(?<device>[A-Za-z0-9_:\[\].-]+)\s+KV buffer size\s*=\s*(?<size>[0-9.]+)\s*MiB'){$where=if($matches.device-match'(?i)CPU|Host'){'CPU'}else{'GPU'};$k="${where}KV";$tot[$k]+=[double]$matches.size;$seen[$k]=$true}
  if($line -match '(?i)(?<device>[A-Za-z0-9_:\[\].-]+)\s+compute buffer size\s*=\s*(?<size>[0-9.]+)\s*MiB'){$where=if($matches.device-match'(?i)CPU|Host'){'CPU'}else{'GPU'};$k="${where}Compute";$tot[$k]+=[double]$matches.size;$seen[$k]=$true}
  if($line -match '(?i)(?<device>[A-Za-z0-9_:\[\].-]+)\s+output buffer size\s*=\s*(?<size>[0-9.]+)\s*MiB'){$where=if($matches.device-match'(?i)CPU|Host'){'CPU'}else{'GPU'};$k="${where}Output";$tot[$k]+=[double]$matches.size;$seen[$k]=$true}
  if($line -match '(?i)offloaded\s+(?<gpu>\d+)\s*/\s*(?<total>\d+)\s+layers?\s+to\s+GPU'){$gpuLayers=[int]$matches.gpu;$totalLayers=[int]$matches.total}
  if($line -match '(?i)n_ctx_slot\s*=\s*(?<ctx>\d+)'){$runtimeContext=[int]$matches.ctx}elseif($line -match '(?i)n_ctx(?:_per_seq|_seq)?\s*=\s*(?<ctx>\d+)'){$runtimeContext=[int]$matches.ctx}
  if($line -match '(?i)n_batch\s*=\s*(?<v>\d+)'){$nBatch=[int]$matches.v};if($line -match '(?i)n_ubatch\s*=\s*(?<v>\d+)'){$nUbatch=[int]$matches.v}
  if($line -match "(?i)loaded multimodal model,\s*'(?<path>[^']+)'" ){$mmprojPath=$matches.path};if($line -match '(?i)(CLIP|mtmd).*using\s+(?<backend>.+?)\s+backend'){$mmprojBackend=$matches.backend.Trim()};if($line-match'(?i)draft|MTP|speculat'){$mtp=$true};if($line-match'(?i)require at minimum 1024 image tokens'){$imageWarning=$true}
 }
 $command=Get-CommandText;$requested=Get-CommandFlagValue $command '-c';$fit=Get-CommandFlagValue $command '--fit-ctx';if($command-match'--no-mmproj-offload'){$mmprojBackend='CPU (--no-mmproj-offload)'}
 $s=New-Object Collections.Generic.List[string];if($SourceName){$s.Add("Source log                 : $SourceName")};$s.Add('');$s.Add('CONTEXT / BATCH');$s.Add("  Requested context        : $(if($requested){$requested}else{'unknown'})");$s.Add("  Auto-fit minimum         : $(if($fit){$fit}else{'not configured'})");$s.Add("  Runtime context          : $(if($null-ne$runtimeContext){$runtimeContext}else{'not captured'})");if($requested-and$null-ne$runtimeContext-and[int64]$runtimeContext-lt[int64]$requested){$s.Add('  WARNING                  : runtime context is below requested context')};$s.Add("  Runtime n_batch          : $(if($null-ne$nBatch){$nBatch}else{'not captured'})");$s.Add("  Runtime n_ubatch         : $(if($null-ne$nUbatch){$nUbatch}else{'not captured'})");$s.Add('');$s.Add('MODEL / OFFLOAD');$s.Add("  GPU model buffers        : $(Format-MiB $tot.GPUModel $seen.GPUModel)");$s.Add("  CPU model buffers        : $(Format-MiB $tot.CPUModel $seen.CPUModel)");$s.Add("  GPU layers               : $(if($null-ne$gpuLayers){"$gpuLayers / $totalLayers"}else{'not captured in current log'})");$s.Add('');$s.Add('KV / COMPUTE');$s.Add("  KV GPU                   : $(Format-MiB $tot.GPUKV $seen.GPUKV)");$s.Add("  KV CPU                   : $(Format-MiB $tot.CPUKV $seen.CPUKV)");$s.Add("  Compute GPU              : $(Format-MiB $tot.GPUCompute $seen.GPUCompute)");$s.Add("  Compute CPU              : $(Format-MiB $tot.CPUCompute $seen.CPUCompute)");$s.Add("  Output GPU               : $(Format-MiB $tot.GPUOutput $seen.GPUOutput)");$s.Add("  Output CPU               : $(Format-MiB $tot.CPUOutput $seen.CPUOutput)");$s.Add('');$s.Add('MULTIMODAL / MTP');$s.Add("  mmproj backend           : $mmprojBackend");if($mmprojPath){$s.Add("  mmproj file              : $mmprojPath")};$s.Add("  MTP/speculative detected : $mtp");$s.Add("  1024 image-token warning : $imageWarning")
 return[pscustomobject]@{Summary=$s-join"`r`n";Raw=if($interesting.Count-gt 0){($interesting|Select-Object -Last 400)-join"`r`n"}else{'No matching llama.cpp runtime lines yet.'}}
}
function Get-SlotSummary{param($SlotsResponse);[object[]]$slots=@();if($null-ne$SlotsResponse){if($SlotsResponse-is[System.Array]){[object[]]$slots=$SlotsResponse}else{[object[]]$slots=@($SlotsResponse)}};if($slots.Length-eq 0){return'No slot data available.'};$lines=New-Object Collections.Generic.List[string];foreach($slot in$slots){$id=Get-SafeProperty $slot'id''?';$ctx=Get-SafeProperty $slot'n_ctx''?';$processing=Get-SafeProperty $slot'is_processing'$false;$next=Get-SafeProperty $slot'next_token'$null;$decoded=Get-SafeProperty $next'n_decoded''?';$prompt=Get-SafeProperty $next'n_prompt_tokens_processed''?';$lines.Add("Slot $id : context=$ctx | processing=$processing | decoded=$decoded | prompt_processed=$prompt")};return$lines-join"`r`n"}
function Get-MetricsSummary{param([string]$Metrics);if([string]::IsNullOrWhiteSpace($Metrics)){return'Metrics unavailable. Restart llama-server so --metrics is active.'};[string[]]$wanted=@($Metrics-split"`r?`n"|Where-Object{$_-notmatch'^#'-and$_-match'(?i)(tokens|prompt|predicted|requests|seconds|cache|draft|speculat|slots)'});if($wanted.Length-eq 0){return'Metrics endpoint responded, but no selected counters matched.'};return($wanted|Select-Object -Last 180)-join"`r`n"}
function Get-DiagnosticsSnapshot{$health=Get-JsonEndpoint'/health';$slots=Get-JsonEndpoint'/slots';$metrics=Get-TextEndpoint'/metrics';$proc=Get-CurrentProcessInfo;$sys=Get-SystemMemoryInfo;$analysis=Get-LogAnalysis;$healthStatus=[string](Get-SafeProperty $health'status''offline');if([string]::IsNullOrWhiteSpace($healthStatus)){$healthStatus=if($health){'responding'}else{'offline'}};$o=New-Object Collections.Generic.List[string];$o.Add("Health                  : $healthStatus");$o.Add("Endpoint                : http://${HostAddress}:$Port");if($Profile){$o.Add("Launcher profile        : $Profile")};if($proc){$o.Add("PID                     : $($proc.Pid)");$o.Add("Process working set     : $($proc.WorkingSetMB) MB");$o.Add("Process private memory  : $($proc.PrivateMB) MB");if($null-ne$proc.GpuDedicatedMB){$o.Add("Process dedicated VRAM  : $($proc.GpuDedicatedMB) MB")};if($null-ne$proc.GpuSharedMB){$o.Add("Process shared GPU RAM  : $($proc.GpuSharedMB) MB")};$o.Add("Process CPU time        : $($proc.CpuSeconds) s");$o.Add("Process threads         : $($proc.Threads)")};if($sys){$o.Add('');$o.Add("System RAM used         : $($sys.UsedMB) / $($sys.TotalMB) MB");$o.Add("System RAM available    : $($sys.AvailableMB) MB");if($null-ne$sys.CommitMB){$o.Add("System commit           : $($sys.CommitMB) / $($sys.CommitLimitMB) MB")}};$o.Add('');$o.Add('SLOTS');$o.Add((Get-SlotSummary $slots));$m=New-Object Collections.Generic.List[string];$m.Add('LIVE WINDOWS MEMORY');if($proc){$m.Add("  Dedicated VRAM (PID)   : $(if($null-ne$proc.GpuDedicatedMB){"$($proc.GpuDedicatedMB) MB"}else{'not exposed'})");$m.Add("  Shared GPU RAM (PID)   : $(if($null-ne$proc.GpuSharedMB){"$($proc.GpuSharedMB) MB"}else{'not exposed'})");$m.Add("  Working set            : $($proc.WorkingSetMB) MB");$m.Add("  Private memory         : $($proc.PrivateMB) MB")};if($sys){$m.Add("  System RAM used        : $($sys.UsedMB) / $($sys.TotalMB) MB");if($null-ne$sys.CommitMB){$m.Add("  System commit          : $($sys.CommitMB) / $($sys.CommitLimitMB) MB")}};$m.Add('');$m.Add('LLAMA.CPP ALLOCATION FROM STARTUP LOG');$m.Add($analysis.Summary);if($null-ne$slots){$slotsJson=$slots|ConvertTo-Json -Depth 20}else{$slotsJson='No /slots response.'};return[pscustomobject]@{Health=$healthStatus;Overview=$o-join"`r`n";Memory=$m-join"`r`n";Performance=(Get-MetricsSummary $metrics)+"`r`n`r`nRECENT LLAMA.CPP LINES`r`n"+$analysis.Raw;Command=Get-CommandText;SlotsJson=$slotsJson;Raw=$analysis.Raw}}
function New-DiagnosticsForm{$surface=[Drawing.Color]::FromArgb(20,21,24);$panel=[Drawing.Color]::FromArgb(28,29,33);$text=[Drawing.Color]::FromArgb(242,243,245);$accent=[Drawing.Color]::FromArgb(88,184,255);$form=New-Object Windows.Forms.Form;$form.Text='Qwen Local Launcher - Runtime diagnostics';$form.Size=New-Object Drawing.Size(1120,820);$form.MinimumSize=New-Object Drawing.Size(900,680);$form.StartPosition='CenterScreen';$form.BackColor=$surface;$form.ForeColor=$text;$form.Font=New-Object Drawing.Font('Segoe UI',9.5);$header=New-Object Windows.Forms.Panel;$header.Dock='Top';$header.Height=86;$header.BackColor=$panel;$form.Controls.Add($header);$title=New-Object Windows.Forms.Label;$title.Text='Runtime diagnostics';$title.AutoSize=$true;$title.ForeColor=$text;$title.Font=New-Object Drawing.Font('Segoe UI',16,[Drawing.FontStyle]::Bold);$title.Location=New-Object Drawing.Point(22,13);$header.Controls.Add($title);$status=New-Object Windows.Forms.Label;$status.AutoSize=$true;$status.ForeColor=$accent;$status.Location=New-Object Drawing.Point(24,51);$header.Controls.Add($status);$tabs=New-Object Windows.Forms.TabControl;$tabs.Dock='Fill';$form.Controls.Add($tabs);$tabs.BringToFront();$boxes=@{};foreach($name in@('Overview','Memory / offload','Performance','Command','Slots JSON','Raw llama.cpp')){$tab=New-Object Windows.Forms.TabPage;$tab.Text=$name;$tab.BackColor=$surface;$tab.ForeColor=$text;$tab.Padding=New-Object Windows.Forms.Padding(16);[void]$tabs.TabPages.Add($tab);$box=New-Object Windows.Forms.TextBox;$box.Multiline=$true;$box.ReadOnly=$true;$box.Dock='Fill';$box.ScrollBars='Both';$box.WordWrap=$false;$box.BackColor=$surface;$box.ForeColor=$text;$box.BorderStyle='None';$box.Font=New-Object Drawing.Font('Consolas',10);$tab.Controls.Add($box);$boxes[$name]=$box};return[pscustomobject]@{Form=$form;Status=$status;Boxes=$boxes}}
try{if($SelfTest){$slot=[pscustomobject]@{id=0;n_ctx=160000;is_processing=$false};if((Get-SlotSummary $slot)-notmatch'160000'){throw'Single-slot self-test failed.'};$sample=@('load_tensors: offloaded 64/65 layers to GPU','load_tensors: Vulkan0 model buffer size = 12000.00 MiB','load_tensors: CPU_Mapped model buffer size = 650.00 MiB','llama_context: Vulkan_Host output buffer size = 4.00 MiB','llama_kv_cache: Vulkan0 KV buffer size = 2048.00 MiB','llama_context: Vulkan0 compute buffer size = 700.00 MiB','llama_context: n_ctx = 160000','llama_context: n_batch = 1024','llama_context: n_ubatch = 128');$parsed=Get-LogAnalysis -Lines $sample -SourceName'self-test.log';if($parsed.Summary-notmatch'64 / 65'-or$parsed.Summary-notmatch'2048'-or$parsed.Summary-notmatch'160000'){throw'Log parser self-test failed.'};$ui=New-DiagnosticsForm;$ui.Form.Dispose();Write-Host'Runtime diagnostics self-test passed.';return};$ui=New-DiagnosticsForm;$form=$ui.Form;$status=$ui.Status;$boxes=$ui.Boxes;$refresh=[System.EventHandler]{try{$s=Get-DiagnosticsSnapshot;$status.Text="Health: $($s.Health)    Endpoint: http://${HostAddress}:$Port    Profile: $Profile";$boxes['Overview'].Text=$s.Overview;$boxes['Memory / offload'].Text=$s.Memory;$boxes['Performance'].Text=$s.Performance;$boxes['Command'].Text=$s.Command;$boxes['Slots JSON'].Text=$s.SlotsJson;$boxes['Raw llama.cpp'].Text=$s.Raw}catch{Write-DiagnosticsError $_;$status.Text="Refresh error: $($_.Exception.Message) - see runtime-diagnostics-error.log"}};$timer=New-Object Windows.Forms.Timer;$timer.Interval=2000;$timer.add_Tick($refresh);$form.add_Shown({$refresh.Invoke($null,[EventArgs]::Empty);$timer.Start()});$form.add_FormClosed({$timer.Stop();$timer.Dispose()});[void]$form.ShowDialog()}catch{Write-DiagnosticsError $_;if($SelfTest){throw};[Windows.Forms.MessageBox]::Show("Runtime diagnostics could not start.`r`n`r`n$($_.Exception.Message)`r`n`r`nDetails: $script:ErrorLog",'Qwen Local Launcher - Diagnostics Error',[Windows.Forms.MessageBoxButtons]::OK,[Windows.Forms.MessageBoxIcon]::Error)|Out-Null}
